variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  # - test
  - deploy
  - migrate

build:
  stage: build
  image: node:8
  script:
    - npm install
    - npm run prepare
  artifacts:
    paths:
      - build/
      - node_modules/

# test:
#   stage: test
#   image: node:8
#   script:
#     - npm run test:mocha
#   only:
#     - staging
#     - production

deploy:
  stage: deploy
  image: obezuk/gitlab-ci-cloudflare:latest
  environment:
    name: "${CI_COMMIT_REF_NAME}"
  script:
    - echo "Deploying to ${CI_ENVIRONMENT_NAME}"
    - >
      if [ "${NEEDS_SET_ENV}" = "true" ]; then eb setenv
        TIER=${CI_ENVIRONMENT_NAME}
        COOKIE_SECRET=${COOKIE_SECRET}
        GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        WORLDBRAIN_WP_CLIENT_ID=${WORLDBRAIN_WP_CLIENT_ID}
        WORLDBRAIN_WP_CLIENT_SECRET=${WORLDBRAIN_WP_CLIENT_SECRET}
        ADMIN_ACCESS_CODE=${ADMIN_ACCESS_CODE}
        AWS_SES_KEY=${AWS_SES_KEY}
        AWS_SES_SECRET=${AWS_SES_SECRET}
        RDS_USERNAME=${RDS_USERNAME}
        RDS_PASSWORD=${RDS_PASSWORD};
      fi
    - eb deploy
  only:
    - staging
    - production

migrate:
  stage: migrate
  image: sequenceiq/alpine-dev
  environment:
    name: "${CI_COMMIT_REF_NAME}"
  script:
    # - echo curl -v "https://staging.memex.cloud/admin/migrate&tier=${CI_ENVIRONMENT_NAME}&access-code=${ADMIN_ACCESS_CODE}"
    - >
      curl -v
      "https://c30qypeazc.execute-api.eu-central-1.amazonaws.com/latest/admin/migrate&tier=${CI_ENVIRONMENT_NAME}&access-code=${ADMIN_ACCESS_CODE}"
      --cookie "mirgrationAccessCode=${ADMIN_ACCESS_CODE}"
  only:
    - staging
    - production
